#!/usr/bin/env python3
"""Rebuild docs/INDEX.md from the frontmatter of every note, and warn about
notes that break the rules in docs/SCHEMA.md.

Usage:  python3 docs/scripts/build_index.py [--check]

--check exits 1 if there are warnings. Without it, warnings are printed and the
index is written anyway. No third-party packages needed.
"""
import sys, re, pathlib, datetime

DOCS = pathlib.Path(__file__).resolve().parent.parent
SCAN = ["ideas", "library", "inbox"]
SKIP_DIRS = {"archive", "templates", "scripts", "assets"}

LENSES = {"hound", "hipster", "hacker", "hustler", "intelligence"}
STATUSES = {"draft", "reviewed", "adopted", "superseded", "rejected"}
EVIDENCE = {"none", "weak", "strong"}
KINDS = {"brief","question","interview","insight","jtbd","flow","wireframe",
         "critique","spec","spike","architecture","data-model","risk",
         "positioning","pricing","channel","teardown","decision","digest",
         "analysis","meta"}

FM = re.compile(r"\A---\r?\n(.*?)\r?\n---\r?\n", re.S)
LINK = re.compile(r"\[[^\]]*\]\(([^)]+)\)")
FENCE = re.compile(r"```.*?```", re.S)
TICK = re.compile(r"`[^`\n]*`")


def strip_code(text):
    """Links inside code samples are illustrations, not real links."""
    return TICK.sub("", FENCE.sub("", text))

warnings = []


def parse_frontmatter(text):
    """Tiny YAML subset: `key: value` at top level. Good enough for this schema."""
    m = FM.match(text)
    if not m:
        return None
    out = {}
    for line in m.group(1).splitlines():
        if not line.strip() or line.lstrip().startswith("#") or line.startswith((" ", "\t", "-")):
            continue
        if ":" not in line:
            continue
        k, v = line.split(":", 1)
        v = v.strip().strip('"').strip("'")
        out[k.strip()] = v
    return out


def collect():
    notes = []
    for top in SCAN:
        root = DOCS / top
        if not root.exists():
            continue
        for p in sorted(root.rglob("*.md")):
            if any(part in SKIP_DIRS for part in p.relative_to(DOCS).parts):
                continue
            rel = p.relative_to(DOCS).as_posix()
            text = p.read_text(encoding="utf-8")
            fm = parse_frontmatter(text)
            if fm is None:
                warnings.append(f"{rel}: no frontmatter block")
                continue
            if fm.get("kind") == "meta":
                continue
            validate(rel, fm, text, p)
            fm["_path"] = rel
            notes.append(fm)
    return notes


def validate(rel, fm, text, path):
    for field in ("title", "kind", "status", "source", "created"):
        if not fm.get(field):
            warnings.append(f"{rel}: `{field}` is empty")
    lens = fm.get("lens", "")
    if lens and lens not in LENSES:
        warnings.append(f"{rel}: lens '{lens}' is not one of {sorted(LENSES)}")
    if fm.get("status") not in STATUSES:
        warnings.append(f"{rel}: status '{fm.get('status')}' is not valid")
    if fm.get("evidence") and fm["evidence"] not in EVIDENCE:
        warnings.append(f"{rel}: evidence '{fm['evidence']}' is not valid")
    if fm.get("kind") and fm["kind"] not in KINDS:
        warnings.append(f"{rel}: kind '{fm['kind']}' is not in SCHEMA.md")
    if " " in path.name:
        warnings.append(f"{rel}: filename has spaces, use kebab-case")
    if lens == "hound" and fm.get("evidence") == "strong" and fm.get("source", "").split()[0] not in ("me", "interview"):
        warnings.append(f"{rel}: hound note claims strong evidence but source is a model")
    for target in LINK.findall(strip_code(text)):
        if target.startswith(("http://", "https://", "#", "mailto:")):
            continue
        if not (path.parent / target.split("#")[0]).exists():
            warnings.append(f"{rel}: broken link -> {target}")


def table(rows, cols):
    head = "| " + " | ".join(cols) + " |"
    sep = "|" + "---|" * len(cols)
    body = "\n".join("| " + " | ".join(r) + " |" for r in rows)
    return "\n".join([head, sep, body]) if rows else "_none yet_"


def link(fm):
    return f"[{fm.get('title','(untitled)')}]({fm['_path']})"


def main():
    notes = collect()
    today = datetime.date.today().isoformat()
    out = [
        "---", "title: Index", "kind: meta", f"updated: {today}", "---", "",
        "# Index", "",
        "Generated by `docs/scripts/build_index.py`. **Do not edit by hand.**",
        f"{len(notes)} artifacts.", "",
    ]

    drafts = [n for n in notes if n.get("status") == "draft"]
    out += ["## Still in draft", "",
            "Notes nobody has properly read yet. Shortest path to a tidy vault is"
            " reading these and promoting or rejecting them.", "",
            table([[link(n), n.get("lens", "-"), n.get("kind", "-"), n.get("source", "-"), n.get("created", "-")]
                   for n in sorted(drafts, key=lambda n: n.get("created", ""))],
                  ["note", "lens", "kind", "source", "created"]), ""]

    questions = [n for n in notes if n.get("kind") == "question" and n.get("status") != "adopted"]
    out += ["## Open questions", "",
            table([[link(n), n.get("lens", "-"), n.get("idea", "-")] for n in questions],
                  ["question", "lens", "idea"]), ""]

    out += ["## By lens", ""]
    for lens in ["hound", "hipster", "hacker", "hustler", "intelligence"]:
        rows = [[link(n), n.get("idea", "-"), n.get("kind", "-"), n.get("status", "-"),
                 n.get("evidence", "-"), n.get("source", "-")]
                for n in notes if n.get("lens") == lens]
        out += [f"### {lens}", "",
                table(rows, ["note", "idea", "kind", "status", "evidence", "source"]), ""]

    others = [n for n in notes if n.get("lens", "") not in LENSES]
    if others:
        out += ["### no lens (library, inbox)", "",
                table([[link(n), n.get("kind", "-"), n.get("status", "-"), n.get("source", "-")] for n in others],
                      ["note", "kind", "status", "source"]), ""]

    if warnings:
        out += ["## Warnings", "",
                "Fix these, then rerun the script.", ""] + [f"- {w}" for w in warnings] + [""]

    (DOCS / "INDEX.md").write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {DOCS/'INDEX.md'} — {len(notes)} artifacts, {len(warnings)} warnings")
    for w in warnings:
        print("  !", w)
    if warnings and "--check" in sys.argv:
        sys.exit(1)


if __name__ == "__main__":
    main()
